-- MySQL Script generated by MySQL Workbench
-- 05/03/14 18:46:53
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sc3d_uni
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sc3d_uni` ;
CREATE SCHEMA IF NOT EXISTS `sc3d_uni` DEFAULT CHARACTER SET latin1 ;
USE `sc3d_uni` ;

-- -----------------------------------------------------
-- Table `sc3d_uni`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc3d_uni`.`roles` ;

CREATE TABLE IF NOT EXISTS `sc3d_uni`.`roles` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc3d_uni`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc3d_uni`.`users` ;

CREATE TABLE IF NOT EXISTS `sc3d_uni`.`users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(254) BINARY NOT NULL,
  `username` VARCHAR(32) BINARY NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `logins` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `last_login` INT(10) UNSIGNED NULL,
  `super_usuario` TINYINT(1) NOT NULL DEFAULT '0',
  `nombre_completo` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_username` (`username` ASC),
  UNIQUE INDEX `uniq_email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc3d_uni`.`roles_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc3d_uni`.`roles_users` ;

CREATE TABLE IF NOT EXISTS `sc3d_uni`.`roles_users` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_role_id` (`role_id` ASC),
  CONSTRAINT `roles_users_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sc3d_uni`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `roles_users_ibfk_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `sc3d_uni`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc3d_uni`.`user_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc3d_uni`.`user_tokens` ;

CREATE TABLE IF NOT EXISTS `sc3d_uni`.`user_tokens` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `user_agent` VARCHAR(40) NOT NULL,
  `token` VARCHAR(40) NOT NULL,
  `created` INT(10) UNSIGNED NOT NULL,
  `expires` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_token` (`token` ASC),
  INDEX `fk_user_id` (`user_id` ASC),
  INDEX `expires` (`expires` ASC),
  CONSTRAINT `user_tokens_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sc3d_uni`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc3d_uni`.`carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc3d_uni`.`carreras` ;

CREATE TABLE IF NOT EXISTS `sc3d_uni`.`carreras` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sc3d_uni`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc3d_uni`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `sc3d_uni`.`alumnos` (
  `carreras_id` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `matricula` VARCHAR(25) BINARY NOT NULL,
  PRIMARY KEY (`carreras_id`, `users_id`),
  INDEX `fk_alumnos_carreras1_idx` (`carreras_id` ASC),
  INDEX `fk_alumnos_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_alumnos_carreras1`
    FOREIGN KEY (`carreras_id`)
    REFERENCES `sc3d_uni`.`carreras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sc3d_uni`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sc3d_uni`.`docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc3d_uni`.`docentes` ;

CREATE TABLE IF NOT EXISTS `sc3d_uni`.`docentes` (
  `users_id` INT(11) UNSIGNED NOT NULL,
  `usuario_uni` VARCHAR(20) BINARY NOT NULL,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_docentes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sc3d_uni`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sc3d_uni`.`empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc3d_uni`.`empresas` ;

CREATE TABLE IF NOT EXISTS `sc3d_uni`.`empresas` (
  `users_id` INT(11) UNSIGNED NOT NULL,
  `rfc` VARCHAR(45) BINARY NOT NULL,
  PRIMARY KEY (`users_id`),
  INDEX `fk_empresas_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_empresas_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sc3d_uni`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sc3d_uni`.`cotizacions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc3d_uni`.`cotizacions` ;

CREATE TABLE IF NOT EXISTS `sc3d_uni`.`cotizacions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `nombre_pieza` VARCHAR(45) NOT NULL,
  `precio_cartucho` FLOAT NOT NULL,
  `precio_pad` FLOAT NOT NULL,
  `proceso_limpieza` FLOAT NOT NULL,
  `rem` FLOAT NOT NULL,
  `peso_pieza` FLOAT NOT NULL,
  `peso_soporte` FLOAT NOT NULL,
  `iva` FLOAT NOT NULL,
  `imagen` VARCHAR(50) NOT NULL,
  `impresa` TINYINT(1) NOT NULL DEFAULT '0',
  `users_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_cotizacions_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_cotizacions_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sc3d_uni`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sc3d_uni`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `sc3d_uni`;
INSERT INTO `sc3d_uni`.`roles` (`id`, `name`, `description`) VALUES (1, 'login', 'Login privileges, granted after account confirmation');
INSERT INTO `sc3d_uni`.`roles` (`id`, `name`, `description`) VALUES (2, 'admin', 'Administrative user, has access to everything.');

COMMIT;

